{"level":"info","datetime":"2021-04-03T16:40:57.902Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"error","datetime":"2021-04-03T16:40:57.904Z","logger":"main.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\nmain.main\n\t/app/main.go:30\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"info","datetime":"2021-04-03T18:44:46.287Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"error","datetime":"2021-04-03T18:44:46.297Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:44:56.303Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:45:06.310Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:45:16.327Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:45:26.338Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:45:36.350Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:45:46.356Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","datetime":"2021-04-03T18:45:56.360Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\ngithub.com/manabie-com/togo/internal/transport.NewServer\n\t/app/internal/transport/server.go:19\nmain.main\n\t/app/main.go:29\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"info","datetime":"2021-04-03T18:46:55.972Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-03T18:46:55.993Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"error","datetime":"2021-04-03T18:46:55.994Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Cannot start server","type":"process","error":"listen tcp: address 5050: missing port in address","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\nmain.main\n\t/app/main.go:31\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"info","datetime":"2021-04-03T18:49:14.474Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-03T18:49:14.478Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"error","datetime":"2021-04-03T18:49:14.479Z","logger":"main.Server.Postgres","caller":"logs/log.go:44","msg":"Cannot start server","type":"process","error":"listen tcp: address 5050: missing port in address","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\nmain.main\n\t/app/main.go:31\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"info","datetime":"2021-04-03T18:50:16.283Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-03T18:50:16.287Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T03:31:40.696Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T03:31:40.776Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T03:31:44.177Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T03:31:47.220Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T03:33:43.123Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T03:33:43.142Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T03:33:46.182Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T03:46:20.350Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T03:46:20.359Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T06:57:56.494Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T06:57:56.525Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:00:02.132Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:00:02.144Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:00:49.717Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:00:49.721Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:03:20.915Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:03:20.921Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:04:32.014Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:04:32.018Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:05:37.287Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:05:37.290Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:22:33.702Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:22:33.707Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:36:13.551Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:36:13.555Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:42:58.893Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:42:58.897Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:44:34.083Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T07:44:34.087Z","logger":"main.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T08:52:02.033Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"error","datetime":"2021-04-04T08:52:02.036Z","logger":"main.Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.2:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:77\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:45\nmain.main\n\t/app/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"info","datetime":"2021-04-04T08:52:25.862Z","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T08:52:25.867Z","logger":"main.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"error","datetime":"2021-04-04T23:18:42.070+0700","logger":"main","caller":"logs/log.go:44","msg":"error loading config","type":"process","error":"Config File \"app.stg\" Not Found in \"[/Users/edarha/Desktop/EdarHa/workspace/togo/configs]\"","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/Users/edarha/Desktop/EdarHa/workspace/togo/internal/logs/log.go:44\nmain.main\n\t/Users/edarha/Desktop/EdarHa/workspace/togo/main.go:23\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
{"level":"info","datetime":"2021-04-04T23:18:42.072+0700","logger":"main","caller":"logs/log.go:39","msg":"Server is running","type":"process","error":null}
